name: full_install

on:
  [push]


jobs:
  install:
    runs-on: ubuntu-18.04
    steps:
    - name: run bootstrap script
      run: |
        printf '' | bash -c "$(curl -s https://raw.githubusercontent.com/Submitty/Submitty/master/.setup/bootstrap.sh)"