name: full_install

on:
  [push]

jobs:
  install:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: run bootstrap script
      run: |
        echo -e "localhost
          5432
          submitty_dbuser
          submitty_dbuser
          America/New_York
          http://localhost


          sysadmin@example.com
          https://example.com
          ${AUTH_METHOD}


          y


          submitty@vagrant
          do-not-reply@vagrant
          localhost
          25" | sudo bash -c "$(curl -s https://raw.githubusercontent.com/Submitty/Submitty/master/.setup/bootstrap.sh)"