name: full_install

on:
  [push]

jobs:
  install:
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_PASSWORD: submitty_dbuser
          POSTGRES_USER: submitty_dbuser
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: run bootstrap script
      run: |
        echo -e "localhost
          5432
          submitty_dbuser
          submitty_dbuser
          America/New_York
          http://localhost


          sysadmin@example.com
          https://example.com
          1


          y


          submitty@vagrant
          do-not-reply@vagrant
          localhost
          25" | sudo bash -c "$(curl -s https://raw.githubusercontent.com/Submitty/Submitty/master/.setup/bootstrap.sh)"