name: William's GitHub Actions Testing

on: [push]

jobs:
  vagrant-up:
    runs-on: macos-10.15
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}-${{ hashFiles('.setup') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}-${{ hashFiles('.setup') }}

      - name: run vagrant up
        run: vagrant up

      - name: ssh into machine
        run: vagrant ssh
